# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Set MyRunNumber
variables: 
  uiSource: "."
  uiBuild: "$(uiSource)/dist"
  BuildNumber: '1.0.0-CI-$(Build.BuildNumber)'
  tag: '$(Build.BuildNumber)'

name: 1.0$(Rev:.r)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: Archive
  inputs:
    rootFolderOrFile: '$(uiBuild)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: Bash@3
  displayName: Deploy to heroku
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      git checkout $(Build.SourceBranchName)
      git remote add heroku https://heroku:$PAT@git.heroku.com/abhishek1950mean.git
      git push heroku $(Build.SourceBranchName)
      echo 'Hello world'
    workingDirectory: '.'
    
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: 'docker-service-connection'

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'docker-service-connection'
    repository: 'abhishek1950/mean'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)
      latest

- task: Docker@2
  displayName: Logout of Docker Hub
  inputs:
    command: logout
    containerRegistry: 'docker-service-connection'